[package]
name = "spot-server"
version = "0.1.0"
authors = ["teovoinea <voinea.teodor@gmail.com>"]

[dependencies]
serde = "1.0"
websocket = "0.20.2"
hyper = "0.11.21"
image = "*"
serde_derive = "1.0.27"
bincode = "1.0.0"