[package]
name = "spot-server"
version = "0.1.0"
authors = ["teovoinea <voinea.teodor@gmail.com>"]

[dependencies]
serde = "1.0"
ws = "0.8.0"
image = "*"
serde_derive = "1.0.27"
bincode = "1.0.0"
lazy_static = "1.0.0"
env_logger = "0.6.0"
log = "0.4.1"